# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FractalPolygon
                                 A QGIS plugin
 Tranform simple polygons into fractal polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-27
        copyright            : (C) 2026 by Fragmentos Olvidados Software
        email                : denet.demina@gmail.com
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox

try:
    from .resources import *
except ImportError:
    class Resources:
        def __init__(self):
            pass
    import sys
    sys.modules['FractalPolygon.resources'] = Resources()
from .Fractal_dialog import FractalPolygonDialog
import os.path

import random
import math
from qgis.core import (
    QgsProject, 
    QgsVectorLayer, 
    QgsFeature, 
    QgsGeometry, 
    QgsPointXY, 
    QgsMessageLog, 
    Qgis,
    QgsWkbTypes
)

def generar_fractal_linea(p1, p2, profundidad, intensidad, rugosidad):
    """Algoritmo de Desplazamiento de Punto Medio para crear el fractal"""
    if profundidad <= 0:
        return [p1]
    
    mx = (p1.x() + p2.x()) / 2
    my = (p1.y() + p2.y()) / 2
    
    dx = p2.x() - p1.x()
    dy = p2.y() - p1.y()
    longitud = math.sqrt(dx**2 + dy**2)
    
    if longitud == 0:
        return [p1]
        
    px = -dy / longitud
    py = dx / longitud
    
    desvio_maximo = longitud * intensidad
    desplazamiento = random.uniform(-desvio_maximo, desvio_maximo)
    
    cx = mx + (px * desplazamiento)
    cy = my + (py * desplazamiento)
    punto_central = QgsPointXY(cx, cy)
    
    nueva_intensidad = intensidad * rugosidad
    
    mitad_izquierda = generar_fractal_linea(p1, punto_central, profundidad - 1, nueva_intensidad, rugosidad)
    mitad_derecha = generar_fractal_linea(punto_central, p2, profundidad - 1, nueva_intensidad, rugosidad)
    
    return mitad_izquierda + mitad_derecha

def procesar_geometria_fractal(geometria, profundidad, intensidad, rugosidad):
    """Detecta el tipo de geometría, resuelve curvas y aplica el algoritmo"""
    
    # Si la geometría es curva (ej. CircularString), la convertimos a recta segmentada
    if QgsWkbTypes.isCurvedType(geometria.wkbType()):
        geometria = QgsGeometry(geometria.constGet().segmentize())

    tipo_geom = geometria.type()

    # --- CASO A: LÍNEAS Y MULTILÍNEAS ---
    if tipo_geom == QgsWkbTypes.LineGeometry:
        if geometria.isMultipart():
            lineas = geometria.asMultiPolyline()
        else:
            lineas = [geometria.asPolyline()]
            
        nuevas_lineas = []
        for linea in lineas:
            nuevos_puntos = []
            for i in range(len(linea) - 1):
                p1 = linea[i]
                p2 = linea[i+1]
                nuevos_puntos.extend(generar_fractal_linea(p1, p2, profundidad, intensidad, rugosidad))
            
            # En líneas abiertas, pegamos el último vértice original al final
            if linea:
                nuevos_puntos.append(linea[-1])
            nuevas_lineas.append(nuevos_puntos)
            
        if geometria.isMultipart():
            return QgsGeometry.fromMultiPolylineXY(nuevas_lineas)
        else:
            return QgsGeometry.fromPolylineXY(nuevas_lineas[0])

    # --- CASO B: POLÍGONOS Y MULTIPOLÍGONOS ---
    elif tipo_geom == QgsWkbTypes.PolygonGeometry:
        if geometria.isMultipart():
            poligonos = geometria.asMultiPolygon()
        else:
            poligonos = [geometria.asPolygon()]
            
        nuevos_poligonos = []
        for poligono in poligonos:
            nuevo_poligono = []
            for anillo in poligono:
                nuevos_puntos = []
                for i in range(len(anillo) - 1):
                    p1 = anillo[i]
                    p2 = anillo[i+1]
                    nuevos_puntos.extend(generar_fractal_linea(p1, p2, profundidad, intensidad, rugosidad))
                
                # En polígonos, cerramos el anillo pegando el primer vértice al final
                if nuevos_puntos:
                    nuevos_puntos.append(nuevos_puntos[0])
                nuevo_poligono.append(nuevos_puntos)
            nuevos_poligonos.append(nuevo_poligono)
            
        if geometria.isMultipart():
            return QgsGeometry.fromMultiPolygonXY(nuevos_poligonos)
        else:
            return QgsGeometry.fromPolygonXY(nuevos_poligonos[0])
            
    # Si detecta puntos, devuelve la geometría intacta por seguridad
    return geometria


class FractalPolygon:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FractalPolygon_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&FractalPolygon')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('FractalPolygon', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True, add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/FractalPolygon/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'FractalPolygon'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&FractalPolygon'), action)
            self.iface.removeToolBarIcon(action)

    def ejecutar_proceso_fractal(self):
        """Lee la interfaz del usuario y genera los fractales en QGIS"""
        F_Capa = self.dlg.F_Capa.currentLayer() 
        
        F_Profundidad = int(self.dlg.F_Profundidad.value())       
        F_Intensidad = float(self.dlg.F_Intensidad.value())
        F_Fractal = float(self.dlg.F_Fractal.value())
        F_Semilla = int(self.dlg.F_Semilla.value())       
        
        if F_Intensidad <= 0.0 or F_Profundidad <= 0:
            QgsMessageLog.logMessage("ALERTA: La intensidad o profundidad es 0 o menor.", "FractalPolygon", Qgis.Warning)
            self.iface.messageBar().pushMessage("Fractal", "Sube la intensidad (> 0) o profundidad (> 0)", level=Qgis.Warning, duration=5)
            return

        if not F_Capa:
            self.iface.messageBar().pushMessage("Fractal", "Selecciona una capa válida.", level=Qgis.Warning, duration=3)
            return

        # --- VALIDACIÓN UNIVERSAL DE GEOMETRÍAS ---
        geom_type = F_Capa.geometryType()
        wkb_type = F_Capa.wkbType()
        
        if geom_type == QgsWkbTypes.PointGeometry or geom_type == QgsWkbTypes.NullGeometry:
            self.iface.messageBar().pushMessage("Fractal", "Las capas de puntos no son compatibles.", level=Qgis.Critical, duration=5)
            return
            
        if geom_type == QgsWkbTypes.LineGeometry:
            tipo_uri = "MultiLineString" if QgsWkbTypes.isMultiType(wkb_type) else "LineString"
        else:
            tipo_uri = "MultiPolygon" if QgsWkbTypes.isMultiType(wkb_type) else "Polygon"

        random.seed(F_Semilla)
        crs_id = F_Capa.crs().authid()
        
        nombre_salida = f"Fractal_{F_Capa.name()}"
        capa_salida = QgsVectorLayer(f"{tipo_uri}?crs={crs_id}", nombre_salida, "memory")
        proveedor_salida = capa_salida.dataProvider()
        
        proveedor_salida.addAttributes(F_Capa.fields())
        capa_salida.updateFields()
        
        # --- CONFIGURACIÓN DE LA BARRA DE PROGRESO ---
        total_features = F_Capa.featureCount()
        if total_features > 0:
            self.dlg.progressBar.setMaximum(total_features)
            self.dlg.progressBar.setValue(0)
        
        nuevas_features = []
        contador = 0
        
        # Bucle de procesamiento
        for feature in F_Capa.getFeatures():
            geom = feature.geometry()
            
            nueva_geom = procesar_geometria_fractal(geom, F_Profundidad, F_Intensidad, F_Fractal)
            
            nueva_feature = QgsFeature()
            nueva_feature.setGeometry(nueva_geom)
            nueva_feature.setAttributes(feature.attributes())
            nuevas_features.append(nueva_feature)
            
            # --- ACTUALIZAR LA BARRA EN CADA VUELTA ---
            contador += 1
            self.dlg.progressBar.setValue(contador)
            QCoreApplication.processEvents() # Evita que la interfaz se congele
            
        # Limpiar la barra al terminar (opcional, la devuelve a 0)
        self.dlg.progressBar.setValue(0)
            
        proveedor_salida.addFeatures(nuevas_features)
        capa_salida.updateExtents()
        
        QgsProject.instance().addMapLayer(capa_salida)
        self.iface.messageBar().pushMessage("Fractal", "¡Proceso terminado con éxito!", level=Qgis.Success, duration=3)


    def run(self):
        if self.first_start == True:
            self.first_start = False
            self.dlg = FractalPolygonDialog()
            self.dlg.Ejecutar.clicked.connect(self.ejecutar_proceso_fractal)

        # --- NUEVO: Generar semilla aleatoria al abrir ---
        # Genera un número entero entre 1 y 99999
        semilla_aleatoria = random.randint(1, 99999)
        # Lo inyecta en el widget de la interfaz
        self.dlg.F_Semilla.setValue(semilla_aleatoria)
        # -------------------------------------------------

        self.dlg.show()
        result = self.dlg.exec_()
        if result:
            pass